# Generated by Django 3.2.6 on 2023-10-03 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='survey',
            name='Q1',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='Q2',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='Q3',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='Q4',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='Q5',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='Q6',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
