# Generated by Django 3.2.6 on 2023-10-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231003_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='Q1',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Q2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Q3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Q4',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Q5',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Q6',
        ),
    ]
