# Generated by Django 3.2.6 on 2023-10-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231003_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='questions',
            new_name='Q1',
        ),
        migrations.AddField(
            model_name='survey',
            name='Q2',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='Q3',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='Q4',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='Q5',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='Q6',
            field=models.JSONField(null=True),
        ),
    ]
