# Generated by Django 3.2.6 on 2023-10-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231003_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('response_timestamp', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('question_name', models.JSONField()),
                ('response', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='Q1',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Q2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Q3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Q4',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Q5',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Q6',
        ),
    ]
